[package]
name = "mehari"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Variant effect prediction all in Rust"
license = "MIT"
homepage = "https://github.com/bihealth/mehari"
readme = "README.md"

[[bin]]
name = "mehari"

[dependencies]
anyhow = "1.0.69"
byteorder = "1.4.3"
clap = { version = "4.1.8", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
csv = "1.2.0"
hgvs = "0.2.0"
log = "0.4.17"
noodles = { version = "0.33.0", features = ["vcf", "bcf", "csi", "fasta", "bgzf", "tabix"] }
noodles-util = { version = "0.5.0", features = ["noodles-bcf", "noodles-bgzf", "noodles-vcf", "variant"] }
rocksdb = "0.20.1"
serde = { version = "1.0.152", features = ["derive"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = "0.3.16"

[dev-dependencies]
pretty_assertions = "1.3.0"
