[package]
name = "mehari"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Variant effect prediction all in Rust"
license = "MIT"
homepage = "https://github.com/bihealth/mehari"
readme = "README.md"

[[bin]]
name = "mehari"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.8", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
log = "0.4.17"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = "0.3.16"
